commands:
- alias: alpha-global *
  command: echo "global alpha"
- alias: charlie-global *
  command: echo "global charlie"
- alias: duplicate *
  command: echo "global duplicate"
- alias: echo-global *
  command: |
    echo "global echo!"
    echo "...global echo!"
- alias: zulu-global *
  command: echo "global zulu"
