name: Only allow PR to main from dev

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'main'


jobs:
  check_branch:
    if: github.head_ref != "dev"
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        # You may pin to the exact commit or the version.
        # uses: superbrothers/close-pull-request@941c41e49ced0c13047ed30146e82bd762e907a9
        uses: superbrothers/close-pull-request@v3.0.0
        with:
          # Post a issue comment just before closing a pull request.
          comment: Only dev can  merge into main. Please submit your PR to the dev branch instead.
